spotify:
  playlist:
    name: "Todays generated playlist"
    description: "Queued station: {station_name} - Latest update: {date_val} @ {time_val} (GMT+2)"
  api:
    version: 'v1'
    authorization:    
      url: "https://accounts.spotify.com/authorize"
      redirect_url: "http://localhost:5000/users/authorization/redirect"
      permissions: "ugc-image-upload playlist-modify-public playlist-read-private"
      token_url: "https://accounts.spotify.com/api/token"

radio_plus:
  url: "wss://web-sock.radioplus.be/socket.io/?EIO=4&transport=websocket"
  channels:
    "radio1": 11
    "radio2": 22
    "klara": 31
    "stubru": 41
    "stubrudetijdloze": 44
    "mnm": 55
    "mnm r&beats": 57
    "stubruhooray": 140
    "stubrubruut": 141
    "stubruuntz": 142