spotify:
  playlist:
    name: "Todays generated playlist"
    description: "Queued station: {station_name} - Latest update: {date_val} @ {time_val} (GMT+2)"
  api:
    version: 'v1'
    authorization:    
      url: "https://accounts.spotify.com/authorize"
      redirect_url: "http://localhost:5000/users/authorization/redirect"
      permissions: "ugc-image-upload playlist-modify-public playlist-read-private"
      token_url: "https://accounts.spotify.com/api/token"